name: cm3-installer
version: '0.2'
summary: Automated installation of cm3 in a specific lab environment
description: |
  You probably don't want this

base: core20
grade: devel
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  rpiboot:
    command: usr/bin/rpiboot -d $SNAP/msd
    plugs: [raw-usb, network-control]
  cm3-installer:
    command: bin/run-cm3-install

parts:
  rpiboot:
    plugin: make
    source: https://github.com/raspberrypi/usbboot.git
    build-packages:
      - pkg-config
      - libusb-1.0-0-dev
    stage-packages:
      - libusb-1.0-0
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/msd
      cp rpiboot $SNAPCRAFT_PART_INSTALL/usr/bin/
      cp -a msd/* $SNAPCRAFT_PART_INSTALL/msd/

  stuff:
    plugin: dump
    source: cm3-installer-data
    stage-packages:
      - curl
      - coreutils
      - parted
      - xz-utils

