name: cm3-installer
version: '0.1'
summary: Automated installation of cm3 in a specific lab environment
description: |
  You probably don't want this

base: core18
grade: devel
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  python:
    command: python3
  rpiboot:
    command: rpiboot -d $SNAP/msd
    plugs: [raw-usb, network-control]
  cm3-installer:
    command: bin/run-cm3-install

parts:
  automationhat:
    plugin: python
    python-packages:
      - automationhat
      - smbus-cffi
    build-packages:
      - python3-dev
      - libffi-dev

  rpiboot:
    plugin: make
    source: https://github.com/raspberrypi/usbboot.git
    override-prime: |
      snapcraftctl prime
      cp $SNAPCRAFT_PART_BUILD/rpiboot $SNAPCRAFT_PRIME/usr/bin/
      cp -a $SNAPCRAFT_PART_BUILD/msd $SNAPCRAFT_PRIME
    build-packages:
      - pkg-config
      - libusb-1.0-0-dev

  stuff:
    plugin: dump
    source: cm3-installer-data
    stage-packages:
      - curl
      - coreutils
      - parted
      - xz-utils

